
services:
  postgres:
    image: postgres:16-alpine
    container_name: democrm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1234}
      POSTGRES_DB: democrm
    ports:
      - "5432:5432"
    volumes:
        # Named volume — data persists across container restarts/recreations
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d democrm"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ---------------------------------------------------------
  # Backend — Node.js + Express API
  # ---------------------------------------------------------
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: democrm-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
  
    environment:
       # Environment variables for backend configuration as of now it is included in docker-compose.yml but can be moved to .env file for better security and management
      PORT: 5000
      JWT_SECRET: "dmfmn%7ttb7b7^%R&8jueu&7ytffe"
      JWT_EXPIRES_IN: "1h"
      REFRESH_TOKEN_SECRET: "jngsier$hglkg45u9@hr43gverg34%"
      REFRESH_TOKEN_EXPIRY: "7d"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "1234"
      DB_NAME: democrm
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  # ---------------------------------------------------------
  # Frontend — React + Vite Dev Server
  # ---------------------------------------------------------
  frontend:
    build:
      context: ./client/demoCrmClient
      dockerfile: Dockerfile
    container_name: democrm-frontend
    restart: unless-stopped
    ports:
      
      - "5173:5173"
   
    depends_on:
      - backend
    networks:
      - app-network

# -----------------------------------------------------------
# Named Volumes
# -----------------------------------------------------------
volumes:
  postgres_data:       # Persistent PostgreSQL data
  # frontend_node_modules and backend_node_modules removed for production image usage

# -----------------------------------------------------------
# Custom Bridge Network
# -----------------------------------------------------------
networks:
  app-network:
    driver: bridge
